name: Build IPA

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          bundle install
          bundle exec pod install

      - name: Build IPA
        run: |
          xcodebuild -workspace pic-re.xcworkspace -scheme YourScheme -configuration Release -destination 'generic/platform=iOS' build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
          xcodebuild -exportArchive -archivePath build/YourScheme.xcarchive -exportPath build -exportOptionsPlist exportOptions.plist

      - name: Rename IPA
        run: mv build/YourScheme.ipa build/AnimeGen.ipa

      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: AnimeGen-IPA
          path: build/AnimeGen.ipa
