name: Nightly Build

on:
  - "push"
  - "workflow_dispatch"
jobs:
  build:
    
    runs-on: macos-13
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Fetch Commit Info
      id: commitinfo
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Build iOS
      run: xcodebuild -workspace "AnimeGen.xcworkspace" -scheme AnimeGen -configuration Release -destination generic/platform=iOS archive -archivePath "build/AnimeGen_Nightly.iOS.xcarchive" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    - name: Package iOS
      run: ./Misc/scripts/package.sh "build/AnimeGen_Nightly.iOS.xcarchive" iOS "AnimeGen_Nightly.${{ steps.commitinfo.outputs.sha_short }}.iOS"
    - name: Upload iOS Symbols
      run: ./Misc/scripts/upload_symbols.sh ${{ secrets.APPCENTER_TOKEN }}
    - name: Upload iOS Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: AnimeGen_Nightly.${{ steps.commitinfo.outputs.sha_short }}.iOS
        path: build/*
        if-no-files-found: error
