name: Build IPA

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Xcode
      run: sudo xcode-select --switch /Applications/Xcode_13.2.1.app/Contents/Developer

    - name: Make ipabuild.sh executable
      run: chmod +x ipabuild.sh

    - name: Run ipabuild.sh
      run: ./ipabuild.sh
