name: Build IPA and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Xcode
      run: sudo xcode-select --switch /Applications/Xcode_13.2.1.app/Contents/Developer

    - name: Make ipabuild.sh executable
      run: chmod +x ipabuild.sh

    - name: Run ipabuild.sh
      run: ./ipabuild.sh

    - name: Archive IPA
      uses: actions/upload-artifact@v2
      with:
        name: ipa-artifact
        path: build/AnimeGen.ipa

  release:
   runs-on: ubuntu-latest
   needs: build
   steps:
   - name: Download IPA Artifact
     uses: actions/download-artifact@v2
     with:
       name: ipa-artifact

   - name: Set up Node.js
     uses: actions/setup-node@v3
     with:
       node-version: '14'

   - name: Install GitHub CLI
     run: npm install -g gh

   - name: Create Release
     run: |
       gh auth login --with-token ${{ secrets.GITHUB_TOKEN }}
       gh release create ${{ github.ref }} './AnimeGen.ipa' --title "Release ${{ github.ref }}" --notes "Release notes for ${{ github.ref }}" --draft false
