name: Build and Publish IPA

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Xcode
      run: sudo xcode-select --switch /Applications/Xcode_13.2.1.app/Contents/Developer

    - name: Make ipabuild.sh executable
      run: chmod +x ipabuild.sh

    - name: Run ipabuild.sh
      run: ./ipabuild.sh

    - name: Archive .ipa
      run: mv build/AnimeGen.ipa $GITHUB_WORKSPACE/AnimeGen.ipa

    - name: Generate Release Body
      id: generate_release_body
      run: echo "::set-output name=body::$(git log --format='%s' -n 1)"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        body: ${{ steps.generate_release_body.outputs.body }}
        draft: false
        prerelease: true

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: $GITHUB_WORKSPACE/AnimeGen.ipa
        asset_name: AnimeGen.ipa
        asset_content_type: application/octet-stream
