name: Build and Release IPA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build IPA
        run: |
          xcodebuild -project AnimeGen.xcodeproj -scheme AnimeGen -configuration Release -destination 'generic/platform=iOS' clean archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -archivePath $PWD/build/AnimeGen.xcarchive
          xcodebuild -exportArchive -archivePath $PWD/build/AnimeGen.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $PWD/build

      - name: Archive and Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: AnimeGen-IPA
          path: $PWD/build/*.ipa
